### Deep Learning basic example 
> Simple demonstration of simple neural network without any tensorflow or pytorch library

In [140]:
# importing packages

import pandas as pd
import numpy as np

In [141]:
# Creating dataset AND

df = pd.DataFrame({'x1':(0,0,1,1),'x2':(0,1,0,1),'y':(0,0,0,1)})

In [142]:
# checking dataframe

df

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [143]:
# create random numbers for weights

w = np.random.randn(3)*1e-4
w

array([5.65296488e-05, 1.79527317e-05, 2.67552391e-05])

In [144]:
# creating own activation function using lambda function

g = lambda inputs,weights : np.where(np.dot(inputs,weights)>0,1,0)

In [145]:
# creating own train function

def train(inputs,targets,weights,eta,n_iteration):
    inputs = np.c_[inputs,-np.ones((len(inputs),1))]
    
    for n in range(n_iteration):
        activation = g(inputs,weights);
        weights -= eta * np.dot(np.transpose(inputs),activation - targets)
        print(inputs)
        print(activation)
        print(activation - targets)
        print(weights)
    return(weights)

In [146]:
inputs = df[['x1','x2']]
target = df['y']

w = train(inputs,target,w,0.005,20)

[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 1 1]
0    0
1    0
2    1
3    0
Name: y, dtype: int64
[-4.94347035e-03  1.79527317e-05  5.02675524e-03]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 0]
0    0
1    0
2    0
3   -1
Name: y, dtype: int64
[5.65296488e-05 5.01795273e-03 2.67552391e-05]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 1 1 1]
0    0
1    1
2    1
3    0
Name: y, dtype: int64
[-4.94347035e-03  1.79527317e-05  1.00267552e-02]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 0]
0    0
1    0
2    0
3   -1
Name: y, dtype: int64
[5.65296488e-05 5.01795273e-03 5.02675524e-03]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
0    0
1    0
2    0
3    0
Name: y, dtype: int64
[5.65296488e-05 5.01795273e-03 5.02675524e-03]
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
0    0
1    0
2    0
3    0
Name: y, dtype: int64
[5.65296488e-05 5.01795273e-03 5.

In [123]:
w

array([ 9.56005316e-06, -1.07119050e-06,  1.00162114e-02])

In [124]:
g(np.c_[inputs,-np.ones((len(inputs),1))],w)

array([0, 0, 0, 0])

In [101]:
# now changing learning rate and iteration

w = train(inputs,target,w,0.0001,2)

In [102]:
w

array([0.25005755, 0.25001096, 0.49990957])

In [96]:
g(np.c_[inputs,-np.ones((len(inputs),1))],w)

array([0, 0, 0, 1])